name: Deploy Prefect flow

on:
  push:
    branches:
      - main

env:
  REPOSITORY: ${{ secrets.REPOSITORY }}
  REGION: europe-central2
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      # - name: Build and Push Image
      #   run: |
      #     IMAGE_NAME=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/flow
      #     docker build -t $IMAGE_NAME:${{ github.sha }} .
      #     docker push $IMAGE_NAME:${{ github.sha }}
      #     docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
      #     docker push $IMAGE_NAME:latest
   
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
      
      - name: Prefect Deploy
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: |
          IMAGE_NAME=$REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/flow
          yq -i '.["deployments"][0]["build"][0]["prefect_docker.deployments.steps.build_docker_image"].image_name = "'$IMAGE_NAME'"' prefect.yaml
          yq -i '.["deployments"][0]["build"][0]["prefect_docker.deployments.steps.build_docker_image"].tag = "${{ github.sha }}"' prefect.yaml
          make prefect-deploy
