name: Deploy Prefect flow

on:
  push:
    branches:
      - main

env:
  REPOSITORY: ${{ secrets.REPOSITORY }}
  REGION: europe-central2
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and Push Image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/flow:${{ github.sha }} .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/flow:${{ github.sha }}
          docker tag $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/flow:${{ github.sha }} $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/flow:latest
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/flow:latest

      - name: Prefect Deploy
        env:
          PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: |
          make prefect-deploy
